# Generated by Django 3.2.5 on 2021-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='suggestions',
            field=models.TextField(default=300, max_length=500),
            preserve_default=False,
        ),
    ]
